version: 0.1.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack iTEAMConsulting.FormHandler.Abstractions\iTEAMConsulting.FormHandler.Abstractions.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 1ari/m47eHoJGgmOFDsCXYZRSQSjb1JFNrZz1T45QeQcwYQAqHOpN9IkcCXwoh3W
  artifact: NuGet